version: '2'
services:
    mymicroserviceapp-app:
        image: mymicroserviceapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mymicroserviceapp-mysql:3306/mymicroserviceapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mymicroserviceapp-mysql:
        extends:
            file: mysql.yml
            service: mymicroserviceapp-mysql
